// <auto-generated />
using System;
using ContextoBd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContextoBd.Migrations
{
    [DbContext(typeof(ContextDb))]
    [Migration("20240223160308_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InfraData.Domain.Models_Entities.Alternativa_RespostasQuiz", b =>
                {
                    b.Property<int>("IDRespostasQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlternativaQuiz")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<int?>("RespostaQuizid")
                        .HasColumnType("int");

                    b.HasKey("IDRespostasQuiz");

                    b.HasIndex("RespostaQuizid");

                    b.ToTable("AlternativaQuiz");
                });

            modelBuilder.Entity("InfraData.Domain.Models_Entities.RespostaQuiz", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PerguntasDasAlternativas")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("id");

                    b.ToTable("RespostaQuizzes");
                });

            modelBuilder.Entity("InfraData.Domain.TabelaQuiz", b =>
                {
                    b.Property<int>("IDPerguntasQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Perguntas")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("RespostaQuizid")
                        .HasColumnType("int");

                    b.HasKey("IDPerguntasQuiz");

                    b.HasIndex("RespostaQuizid");

                    b.ToTable("PerguntasDoQuiz");
                });

            modelBuilder.Entity("InfraData.Domain.Models_Entities.Alternativa_RespostasQuiz", b =>
                {
                    b.HasOne("InfraData.Domain.Models_Entities.RespostaQuiz", null)
                        .WithMany("IDRespostasQuiz")
                        .HasForeignKey("RespostaQuizid");
                });

            modelBuilder.Entity("InfraData.Domain.TabelaQuiz", b =>
                {
                    b.HasOne("InfraData.Domain.Models_Entities.RespostaQuiz", null)
                        .WithMany("IDPerguntasQuiz")
                        .HasForeignKey("RespostaQuizid");
                });

            modelBuilder.Entity("InfraData.Domain.Models_Entities.RespostaQuiz", b =>
                {
                    b.Navigation("IDPerguntasQuiz");

                    b.Navigation("IDRespostasQuiz");
                });
#pragma warning restore 612, 618
        }
    }
}
